name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

            - name: Install dependencies
              run: npm ci

            - name: Check types
              run: npm run build

            - name: Run unit tests
              run: npm run test -- --coverage

    style:
        name: Style
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

            - name: Install dependencies
              run: npm ci

            - name: Check for formatting issues
              run: npm run format:check

            - name: Check for syntax errors
              run: npm run lint -- --max-warnings=0
